// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	config "github.com/hungranger/Go_Resume_ChatBot/pkg/config"
	server "github.com/hungranger/Go_Resume_ChatBot/pkg/server"
)

// Injectors from injector.go:

func InjectServer() (server.HTTPServer, error) {
	iConfig := config.ProvideIniConfig()
	httpServer := server.ProvideServer(iConfig)
	return httpServer, nil
}
